clean_teams_pff_to_cfbd <- function(x){x <- case_when(x == "MIAMI FL" ~ "Miami",
                                                  x == "W VIRGINIA" ~ "West Virginia",
                                                  x == "W MICHIGAN" ~ "Western Michigan",
                                                  x == "N DAK ST" ~ "North Dakota State",
                                                  x == "S CAROLINA" ~ "South Carolina",
                                                  x == "OKLA STATE" ~ "Oklahoma State",
                                                  x == "E CAROLINA" ~ "East Carolina",
                                                  x == "MICH STATE" ~ "Michigan State",
                                                  x == "S ALABAMA" ~ "South Alabama",
                                                  x == "N CAROLINA" ~ "North Carolina",
                                                  x == "COLO STATE" ~ "Colorado State",
                                                  x == "E WASHGTON" ~ "Eastern Washington",
                                                  x == "W KENTUCKY" ~ "Western Kentucky",
                                                  x == "N ILLINOIS" ~ "Northern Illinois",
                                                  x == "FLORIDA ST" ~ "Florida State",
                                                  x == "MIDDLE TN" ~ "Middle Tennessee",
                                                  x == "N IOWA" ~ "Northern Iowa",
                                                  x == "UCONN" ~ "Connecticut",
                                                  x == "DOMINION" ~ "Old Dominion",
                                                  x == "S DAK ST" ~ "South Dakota State",
                                                  x == "TENN STATE" ~ "Tennessee State",
                                                  x == "N COLORADO" ~ "Northern Colorado",
                                                  x == "ILL STATE" ~ "Illinois State",
                                                  x == "N TEXAS" ~ "North Texas",
                                                  x == "S DIEGO ST" ~ "San Diego State",
                                                  x == "WASH STATE" ~ "Washington State",
                                                  x == "N ARIZONA" ~ "Northern Arizona",
                                                  x == "USF" ~ "South Florida",
                                                  x == "FL A&M"  ~ "Florida A&M",
                                                  x == "NC A&T" ~ "North Carolina A&T",
                                                  x == "WEBER ST" ~ "Weber State",
                                                  x == "BOSTON COL" ~ "Boston College",
                                                  x == "ARIZONA ST" ~ "Arizona State",
                                                  x == "OREGON ST" ~ "Oregon State",
                                                  x == "BOISE ST" ~ "Boise State",
                                                  x == "UTAH ST" ~ "Utah State",
                                                  x == "NEW MEX ST" ~ "New Mexico State",
                                                  x == "SM HOUSTON" ~ "Sam Houston State",
                                                  x == "LA TECH" ~ "Louisiana Tech",
                                                  x == "FIU" ~ "Florida International",
                                                  x == "FAU" ~ "Florida Atlantic",
                                                  x == "JACKSON ST" ~ "Jacksonville State",
                                                  x == "MIAMI OH" ~ "Miami (OH)",
                                                  x == "BOWL GREEN" ~ "Bowling Green",
                                                  x == "C MICHIGAN" ~ "Central Michigan",
                                                  x == "N ILLINOIS" ~ "Northern Illinois",
                                                  x == "E MICHIGAN" ~ "Eastern Michigan",
                                                  x == "BALL ST" ~ "Ball State",
                                                  x == "S JOSE ST" ~ "San José State",
                                                  x == "FRESNO ST" ~ "Fresno State",
                                                  x == "HAWAII" ~ "Hawai'i",
                                                  x == "GA TECH" ~ "Georgia Tech",
                                                  x == "VA TECH" ~ "Virginia Tech",
                                                  x == "WAKE" ~ "Wake Forest",
                                                  x == "N TEXAS" ~ "North Texas",
                                                  x == "UTSA" ~ "UT San Antonio",
                                                  x == "MISS ST" ~ "Mississippi State",
                                                  x == "APP ST" ~ "Appalachian State",
                                                  x == "ARK ST" ~ "Arkansas State",
                                                  x == "COAST CAR" ~ "Coastal Carolina",
                                                  x == "GA SOUTHERN" ~ "Georgia Southern",
                                                  x == "GA STATE" ~ "Georgia State",
                                                  x == "JAMES MAD" ~ "James Madison",
                                                  x == "LA LAFAYET" ~ "Louisiana",
                                                  x == "LA MONROE" ~ "Louisiana Monroe",
                                                  x == "SO MISS" ~ "Southern Mississippi",
                                                  x == "TEXAS ST" ~ "Texas State",
                                                  x == "CAL" ~ "California",
                                                  x == "NWESTERN" ~ "Northwestern",
                                                  x == "KANSAS ST" ~ "Kansas State",
                                                  TRUE ~ x)}